"""
ABAQUS Input File Writer
=========================

This module exports meshes to ABAQUS .inp format.

Features:
- *NODE keyword
- *ELEMENT keyword (C3D8, C3D8R, C3D20, C3D27, C3D4, C3D10, C3D6, C3D5)
- *ELSET, *NSET keywords
- *SOLID SECTION keyword
- *MATERIAL keyword
- *SURFACE keyword
- *CONTACT PAIR, *TIE keywords
- Assembly support
- Part support

ABAQUS Element Type Mapping:
- HEX8 -> C3D8 (8-node brick)
- HEX8R -> C3D8R (8-node brick, reduced integration)
- HEX20 -> C3D20 (20-node brick)
- HEX27 -> C3D27 (27-node brick)
- TET4 -> C3D4 (4-node tetrahedron)
- TET10 -> C3D10 (10-node tetrahedron)
- PRISM6 -> C3D6 (6-node wedge)
- PYRAMID5 -> C3D5 (5-node pyramid)

Usage:
    >>> from koomesh.export.abaqus_writer import AbaqusWriter
    >>> writer = AbaqusWriter('output.inp')
    >>> writer.write_mesh(mesh)

    Or using context manager:
    >>> with AbaqusWriter('output.inp') as writer:
    ...     writer.write_header("My Model")
    ...     writer.write_nodes(mesh)
    ...     writer.write_elements(mesh, element_set="ALL_ELEMENTS")
    ...     writer.write_node_set(mesh, "ALL_NODES", list(mesh.nodes.keys()))
    ...     writer.write_section("SECTION1", "ALL_ELEMENTS", "MATERIAL1")
    ...     writer.write_material("MATERIAL1", youngs=210000, poisson=0.3)
"""

import logging
from pathlib import Path
from typing import List, Optional, Dict, Set
from datetime import datetime

from koomesh.meshing.mesh_data import MeshData, ElementType


class AbaqusWriter:
    """
    ABAQUS input file (.inp) writer

    This class writes mesh data to ABAQUS format with support for:
    - Node definitions
    - Element definitions (all element types)
    - Element and node sets
    - Section properties
    - Material definitions
    - Contact definitions
    - Assembly structure

    Attributes:
        output_path: Output file path
        precision: Number of decimal places for coordinates
        reduced_integration: Use reduced integration elements (e.g., C3D8R vs C3D8)
        logger: Logger instance

    Example:
        >>> writer = AbaqusWriter('model.inp', precision=8, reduced_integration=True)
        >>> with writer:
        ...     writer.write_header("Crash Analysis Model")
        ...     writer.write_nodes(mesh)
        ...     writer.write_elements(mesh, "PART1")
        ...     writer.write_section("SEC1", "PART1", "STEEL")
        ...     writer.write_material("STEEL", youngs=210000, poisson=0.3, density=7.85e-9)
    """

    # Element type mapping: KooMesh -> ABAQUS
    ELEMENT_TYPE_MAP = {
        ElementType.HEX8: "C3D8",
        ElementType.HEX20: "C3D20",
        ElementType.HEX27: "C3D27",
        ElementType.TET4: "C3D4",
        ElementType.TET10: "C3D10",
        ElementType.PRISM6: "C3D6",
        ElementType.PYRAMID5: "C3D5",
    }

    # Reduced integration variants
    ELEMENT_TYPE_MAP_R = {
        ElementType.HEX8: "C3D8R",
        ElementType.TET4: "C3D4",  # TET4 has no R variant
        ElementType.PRISM6: "C3D6",  # PRISM6 has no R variant
        ElementType.PYRAMID5: "C3D5",  # PYRAMID5 has no R variant
    }

    def __init__(self,
                 output_path: str,
                 precision: int = 8,
                 reduced_integration: bool = False):
        """
        Initialize ABAQUS writer

        Args:
            output_path: Output .inp file path
            precision: Decimal places for floating point numbers (default: 8)
            reduced_integration: Use reduced integration elements (default: False)
        """
        self.output_path = Path(output_path)
        self.precision = precision
        self.reduced_integration = reduced_integration
        self.logger = logging.getLogger(__name__)

        self.file = None
        self._written_sets = set()  # Track written sets to avoid duplicates

    def __enter__(self):
        """Context manager entry"""
        self.file = open(self.output_path, 'w')
        return self

    def __exit__(self, exc_type, exc_val, exc_tb):
        """Context manager exit"""
        if self.file:
            self.file.close()

    def write_header(self, model_name: str = "KooMesh Model", comments: Optional[List[str]] = None):
        """
        Write ABAQUS file header

        Args:
            model_name: Model name to display in heading
            comments: Optional list of comment lines
        """
        self.file.write("*HEADING\n")
        self.file.write(f"{model_name}\n")
        self.file.write(f"Generated by KooMeshGenerator\n")
        self.file.write(f"Date: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}\n")

        if comments:
            for comment in comments:
                self.file.write(f"** {comment}\n")

        self.file.write("**\n")
        self.logger.debug("Wrote header")

    def write_nodes(self, mesh: MeshData, node_set: Optional[str] = None):
        """
        Write *NODE keyword

        Args:
            mesh: Mesh containing nodes
            node_set: Optional node set name to create automatically
        """
        self.file.write("*NODE\n")

        format_str = "{{:d}}, {{:.{p}e}}, {{:.{p}e}}, {{:.{p}e}}\n".format(p=self.precision)

        for node in mesh.nodes.values():
            line = format_str.format(node.id, node.x, node.y, node.z)
            self.file.write(line)

        self.logger.info(f"Wrote {mesh.num_nodes()} nodes")

        # Optionally create a node set containing all nodes
        if node_set:
            self.write_node_set(mesh, node_set, list(mesh.nodes.keys()))

    def write_elements(self, mesh: MeshData, element_set: str = "ALL_ELEMENTS", part_name: Optional[str] = None):
        """
        Write *ELEMENT keyword

        Args:
            mesh: Mesh containing elements
            element_set: Element set name (default: "ALL_ELEMENTS")
            part_name: Optional part name for organization
        """
        # Get ABAQUS element type
        abaqus_type = self._get_abaqus_element_type(mesh.element_type)

        # Write element keyword with type
        self.file.write(f"*ELEMENT, TYPE={abaqus_type}, ELSET={element_set}\n")

        # Write elements based on type
        if mesh.element_type.is_hex():
            self._write_hex_elements(mesh)
        elif mesh.element_type.is_tet():
            self._write_tet_elements(mesh)
        elif mesh.element_type == ElementType.PRISM6:
            self._write_prism_elements(mesh)
        elif mesh.element_type == ElementType.PYRAMID5:
            self._write_pyramid_elements(mesh)
        else:
            raise ValueError(f"Unsupported element type: {mesh.element_type.code}")

        self.logger.info(f"Wrote {mesh.num_elements()} {abaqus_type} elements")
        self._written_sets.add(element_set)

    def _get_abaqus_element_type(self, elem_type: ElementType) -> str:
        """
        Get ABAQUS element type code

        Args:
            elem_type: KooMesh element type

        Returns:
            ABAQUS element type string (e.g., "C3D8", "C3D8R")
        """
        if self.reduced_integration and elem_type in self.ELEMENT_TYPE_MAP_R:
            return self.ELEMENT_TYPE_MAP_R[elem_type]

        if elem_type not in self.ELEMENT_TYPE_MAP:
            raise ValueError(f"Element type {elem_type.code} not supported in ABAQUS export")

        return self.ELEMENT_TYPE_MAP[elem_type]

    def _write_hex_elements(self, mesh: MeshData):
        """Write hexahedral elements"""
        for elem in mesh.elements.values():
            # ABAQUS format: element_id, n1, n2, n3, n4, n5, n6, n7, n8[, n9-n27]
            node_ids = elem.nodes

            if mesh.element_type == ElementType.HEX8:
                # Single line for HEX8
                line = f"{elem.id}, " + ", ".join(str(nid) for nid in node_ids) + "\n"
                self.file.write(line)

            elif mesh.element_type == ElementType.HEX20:
                # HEX20: corner nodes + edge nodes
                # Line 1: element_id, 8 corner nodes
                line1 = f"{elem.id}, " + ", ".join(str(node_ids[i]) for i in range(8)) + ",\n"
                # Line 2: 12 edge nodes
                line2 = "  " + ", ".join(str(node_ids[i]) for i in range(8, 20)) + "\n"
                self.file.write(line1)
                self.file.write(line2)

            elif mesh.element_type == ElementType.HEX27:
                # HEX27: corner + edge + face + center
                # Line 1: element_id, 8 corner nodes
                line1 = f"{elem.id}, " + ", ".join(str(node_ids[i]) for i in range(8)) + ",\n"
                # Line 2: 12 edge nodes
                line2 = "  " + ", ".join(str(node_ids[i]) for i in range(8, 20)) + ",\n"
                # Line 3: 6 face nodes + 1 center node
                line3 = "  " + ", ".join(str(node_ids[i]) for i in range(20, 27)) + "\n"
                self.file.write(line1)
                self.file.write(line2)
                self.file.write(line3)

    def _write_tet_elements(self, mesh: MeshData):
        """Write tetrahedral elements"""
        for elem in mesh.elements.values():
            node_ids = elem.nodes

            if mesh.element_type == ElementType.TET4:
                # Single line for TET4
                line = f"{elem.id}, " + ", ".join(str(nid) for nid in node_ids) + "\n"
                self.file.write(line)

            elif mesh.element_type == ElementType.TET10:
                # TET10: corner nodes + edge nodes
                # Can fit on one line
                line = f"{elem.id}, " + ", ".join(str(nid) for nid in node_ids) + "\n"
                self.file.write(line)

    def _write_prism_elements(self, mesh: MeshData):
        """Write prism/wedge elements (C3D6)"""
        for elem in mesh.elements.values():
            node_ids = elem.nodes
            # PRISM6: single line with 6 nodes
            line = f"{elem.id}, " + ", ".join(str(nid) for nid in node_ids) + "\n"
            self.file.write(line)

    def _write_pyramid_elements(self, mesh: MeshData):
        """Write pyramid elements (C3D5)"""
        for elem in mesh.elements.values():
            node_ids = elem.nodes
            # PYRAMID5: single line with 5 nodes
            line = f"{elem.id}, " + ", ".join(str(nid) for nid in node_ids) + "\n"
            self.file.write(line)

    def write_node_set(self, mesh: MeshData, set_name: str, node_ids: List[int]):
        """
        Write *NSET keyword

        Args:
            mesh: Mesh data (for validation)
            set_name: Name of the node set
            node_ids: List of node IDs to include
        """
        if set_name in self._written_sets:
            self.logger.warning(f"Node set '{set_name}' already written, skipping")
            return

        self.file.write(f"*NSET, NSET={set_name}\n")

        # Write node IDs, 16 per line (ABAQUS convention)
        for i in range(0, len(node_ids), 16):
            line = ", ".join(str(nid) for nid in node_ids[i:i+16])
            self.file.write(f"  {line}\n")

        self.logger.debug(f"Wrote node set '{set_name}' with {len(node_ids)} nodes")
        self._written_sets.add(set_name)

    def write_element_set(self, mesh: MeshData, set_name: str, element_ids: List[int]):
        """
        Write *ELSET keyword

        Args:
            mesh: Mesh data (for validation)
            set_name: Name of the element set
            element_ids: List of element IDs to include
        """
        if set_name in self._written_sets:
            self.logger.warning(f"Element set '{set_name}' already written, skipping")
            return

        self.file.write(f"*ELSET, ELSET={set_name}\n")

        # Write element IDs, 16 per line
        for i in range(0, len(element_ids), 16):
            line = ", ".join(str(eid) for eid in element_ids[i:i+16])
            self.file.write(f"  {line}\n")

        self.logger.debug(f"Wrote element set '{set_name}' with {len(element_ids)} elements")
        self._written_sets.add(set_name)

    def write_section(self, section_name: str, element_set: str, material_name: str):
        """
        Write *SOLID SECTION keyword

        Args:
            section_name: Section name (for reference)
            element_set: Element set to assign section to
            material_name: Material name to reference
        """
        self.file.write(f"*SOLID SECTION, ELSET={element_set}, MATERIAL={material_name}\n")
        self.logger.debug(f"Wrote section '{section_name}' for elset '{element_set}'")

    def write_material(self,
                      material_name: str,
                      youngs: Optional[float] = None,
                      poisson: Optional[float] = None,
                      density: Optional[float] = None,
                      comments: Optional[List[str]] = None):
        """
        Write *MATERIAL and *ELASTIC keywords

        Args:
            material_name: Material name
            youngs: Young's modulus (E)
            poisson: Poisson's ratio (nu)
            density: Density (mass per unit volume)
            comments: Optional comments about material
        """
        if comments:
            for comment in comments:
                self.file.write(f"** {comment}\n")

        self.file.write(f"*MATERIAL, NAME={material_name}\n")

        if density is not None:
            self.file.write("*DENSITY\n")
            self.file.write(f"{density:.{self.precision}e}\n")

        if youngs is not None and poisson is not None:
            self.file.write("*ELASTIC\n")
            self.file.write(f"{youngs:.{self.precision}e}, {poisson:.{self.precision}e}\n")

        self.logger.debug(f"Wrote material '{material_name}'")

    def write_surface(self, surface_name: str, element_set: str, face: str = "S1"):
        """
        Write *SURFACE keyword

        Args:
            surface_name: Surface name
            element_set: Element set to define surface from
            face: Face identifier (S1, S2, S3, S4, S5, S6 for hex)
        """
        self.file.write(f"*SURFACE, NAME={surface_name}, TYPE=ELEMENT\n")
        self.file.write(f"{element_set}, {face}\n")
        self.logger.debug(f"Wrote surface '{surface_name}' on {element_set}, face {face}")

    def write_tie_constraint(self, name: str, master_surface: str, slave_surface: str):
        """
        Write *TIE constraint (tied contact)

        Args:
            name: Constraint name
            master_surface: Master surface name
            slave_surface: Slave surface name
        """
        self.file.write(f"*TIE, NAME={name}\n")
        self.file.write(f"{slave_surface}, {master_surface}\n")
        self.logger.debug(f"Wrote tie constraint '{name}'")

    def write_contact_pair(self,
                          interaction_name: str,
                          master_surface: str,
                          slave_surface: str,
                          friction: Optional[float] = None):
        """
        Write *CONTACT PAIR keyword

        Args:
            interaction_name: Contact interaction name
            master_surface: Master surface name
            slave_surface: Slave surface name
            friction: Friction coefficient (optional)
        """
        self.file.write(f"*CONTACT PAIR, INTERACTION={interaction_name}\n")
        self.file.write(f"{slave_surface}, {master_surface}\n")

        if friction is not None:
            self.file.write(f"*SURFACE INTERACTION, NAME={interaction_name}\n")
            self.file.write("*FRICTION\n")
            self.file.write(f"{friction:.{self.precision}e}\n")

        self.logger.debug(f"Wrote contact pair '{interaction_name}'")

    def write_complete_model(self,
                            mesh: MeshData,
                            model_name: str = "Model",
                            material_name: str = "Material1",
                            youngs: Optional[float] = None,
                            poisson: Optional[float] = None,
                            density: Optional[float] = None):
        """
        Write a complete ABAQUS model with mesh, section, and material

        Args:
            mesh: Mesh data to export
            model_name: Model name for header
            material_name: Material name
            youngs: Young's modulus (optional)
            poisson: Poisson's ratio (optional)
            density: Density (optional)
        """
        self.write_header(model_name)
        self.write_nodes(mesh)
        self.write_elements(mesh, element_set="ALL_ELEMENTS")
        self.write_section("SECTION1", "ALL_ELEMENTS", material_name)

        if youngs is not None or poisson is not None or density is not None:
            self.write_material(material_name, youngs, poisson, density)

        self.file.write("**\n")
        self.file.write("** End of input file\n")
        self.logger.info(f"Wrote complete model to {self.output_path}")
