"""
ANSYS Database File Writer
===========================

This module exports meshes to ANSYS .cdb (ANSYS Database) format.

Features:
- NBLOCK (node block definition)
- EBLOCK (element block definition)
- ET (element type definition)
- MPDATA (material properties)
- CM/CMBLOCK (component/group definitions)
- TYPE, MAT, REAL, SECNUM commands
- Multiple element types support

ANSYS Element Type Mapping:
- HEX8 -> SOLID185 (8-node hexahedron)
- HEX20 -> SOLID186 (20-node hexahedron)
- HEX27 -> SOLID186 (27-node support in SOLID186)
- TET4 -> SOLID285 (4-node tetrahedron)
- TET10 -> SOLID187 (10-node tetrahedron)
- PRISM6 -> SOLID185 (degenerate to wedge)
- PYRAMID5 -> SOLID185 (degenerate to pyramid)

Usage:
    >>> from koomesh.export.ansys_writer import ANSYSWriter
    >>> writer = ANSYSWriter('output.cdb')
    >>> writer.write_mesh(mesh)

    Or using context manager:
    >>> with ANSYSWriter('output.cdb') as writer:
    ...     writer.write_header("My Model")
    ...     writer.write_element_types(mesh)
    ...     writer.write_nodes(mesh)
    ...     writer.write_elements(mesh)
    ...     writer.write_material("STEEL", youngs=210000, poisson=0.3)
"""

import logging
from pathlib import Path
from typing import List, Optional, Dict, Set
from datetime import datetime

from koomesh.meshing.mesh_data import MeshData, ElementType


class ANSYSWriter:
    """
    ANSYS database file (.cdb) writer

    This class writes mesh data to ANSYS format with support for:
    - Node definitions (NBLOCK)
    - Element definitions (EBLOCK)
    - Element types (ET)
    - Material properties (MPDATA)
    - Component/group definitions (CM, CMBLOCK)
    - Section and real constant assignments

    Attributes:
        output_path: Output file path
        precision: Number of decimal places for coordinates
        logger: Logger instance

    Example:
        >>> writer = ANSYSWriter('model.cdb', precision=8)
        >>> with writer:
        ...     writer.write_header("Analysis Model")
        ...     writer.write_element_types(mesh)
        ...     writer.write_nodes(mesh)
        ...     writer.write_elements(mesh, element_type_id=1, mat_id=1)
        ...     writer.write_material("STEEL", 1, youngs=210000, poisson=0.3)
    """

    # Element type mapping: KooMesh -> ANSYS (element type number)
    ELEMENT_TYPE_MAP = {
        ElementType.HEX8: 185,      # SOLID185 (8-node hexahedron)
        ElementType.HEX20: 186,     # SOLID186 (20-node hexahedron)
        ElementType.HEX27: 186,     # SOLID186 (also supports 27-node)
        ElementType.TET4: 285,      # SOLID285 (4-node tetrahedron)
        ElementType.TET10: 187,     # SOLID187 (10-node tetrahedron)
        ElementType.PRISM6: 185,    # SOLID185 (degenerate wedge)
        ElementType.PYRAMID5: 185,  # SOLID185 (degenerate pyramid)
    }

    # Element type names for documentation
    ELEMENT_TYPE_NAMES = {
        185: "SOLID185",
        186: "SOLID186",
        187: "SOLID187",
        285: "SOLID285",
    }

    def __init__(self,
                 output_path: str,
                 precision: int = 13):
        """
        Initialize ANSYS writer

        Args:
            output_path: Output .cdb file path
            precision: Decimal places for floating point numbers (default: 13)
                      ANSYS typically uses E13.5 format
        """
        self.output_path = Path(output_path)
        self.precision = precision
        self.logger = logging.getLogger(__name__)

        self.file = None
        self._written_components = set()  # Track written components

    def __enter__(self):
        """Context manager entry"""
        self.file = open(self.output_path, 'w')
        return self

    def __exit__(self, exc_type, exc_val, exc_tb):
        """Context manager exit"""
        if self.file:
            self.file.close()

    def write_header(self, title: str = "KooMesh Model", comments: Optional[List[str]] = None):
        """
        Write ANSYS file header

        Args:
            title: Model title
            comments: Optional list of comment lines
        """
        self.file.write("/PREP7\n")
        self.file.write("/COM,*************************************************************\n")
        self.file.write(f"/COM,  {title}\n")
        self.file.write("/COM,  Generated by KooMeshGenerator\n")
        self.file.write(f"/COM,  Date: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}\n")
        self.file.write("/COM,*************************************************************\n")

        if comments:
            for comment in comments:
                self.file.write(f"/COM,  {comment}\n")

        self.file.write("/COM,\n")
        self.logger.debug("Wrote header")

    def write_element_types(self, mesh: MeshData, et_id: int = 1):
        """
        Write ET (Element Type) command

        Args:
            mesh: Mesh containing elements
            et_id: Element type ID (default: 1)
        """
        ansys_type = self._get_ansys_element_type(mesh.element_type)
        type_name = self.ELEMENT_TYPE_NAMES.get(ansys_type, f"SOLID{ansys_type}")

        self.file.write(f"ET,{et_id},{ansys_type}\n")
        self.file.write(f"/COM,  Element Type {et_id}: {type_name}\n")
        self.logger.info(f"Wrote element type: ET {et_id} = {type_name}")

    def _get_ansys_element_type(self, elem_type: ElementType) -> int:
        """
        Get ANSYS element type number

        Args:
            elem_type: KooMesh element type

        Returns:
            ANSYS element type number (e.g., 185, 186, 187, 285)
        """
        if elem_type not in self.ELEMENT_TYPE_MAP:
            raise ValueError(f"Element type {elem_type.code} not supported in ANSYS export")

        return self.ELEMENT_TYPE_MAP[elem_type]

    def write_nodes(self, mesh: MeshData):
        """
        Write NBLOCK (node block) command

        ANSYS NBLOCK format:
        NBLOCK,NumFields,Solid,NodeMax,NodeMin
        (NodeNum, X, Y, Z, RotX, RotY, RotZ)

        Args:
            mesh: Mesh containing nodes
        """
        # NBLOCK header: 6 fields (node, x, y, z, thx, thy, thz), solid model
        num_fields = 6
        node_max = max(mesh.nodes.keys())
        node_min = min(mesh.nodes.keys())

        self.file.write(f"NBLOCK,{num_fields},SOLID,{node_max},{node_min}\n")
        self.file.write("(1i9,3e20.13)\n")  # Format: node ID (i9), coordinates (3 x e20.13)

        # Write nodes
        for node in mesh.nodes.values():
            # ANSYS format: node_id (right-aligned, 9 chars), then 3 coordinates (e20.13)
            line = f"{node.id:9d}{node.x:20.13e}{node.y:20.13e}{node.z:20.13e}\n"
            self.file.write(line)

        self.file.write("N,R5.3,LOC,       -1,\n")  # NBLOCK terminator
        self.logger.info(f"Wrote {mesh.num_nodes()} nodes")

    def write_elements(self, mesh: MeshData, et_id: int = 1, mat_id: int = 1,
                      real_id: int = 0, secnum: int = 0):
        """
        Write EBLOCK (element block) command

        ANSYS EBLOCK format:
        EBLOCK,NumFields,Solid,ElementMax,ElementMin
        (Field1, Field2, ..., NodeList)

        Args:
            mesh: Mesh containing elements
            et_id: Element type ID (default: 1)
            mat_id: Material ID (default: 1)
            real_id: Real constant set ID (default: 0)
            secnum: Section ID (default: 0)
        """
        num_nodes_per_elem = self._get_nodes_per_element(mesh.element_type)
        elem_max = max(mesh.elements.keys())
        elem_min = min(mesh.elements.keys())

        # EBLOCK header
        # Format: 19 integer fields + node list
        self.file.write(f"EBLOCK,19,SOLID,{elem_max},{elem_min}\n")
        self.file.write("(19i9)\n")  # 19 integer fields, 9 chars each

        # Write elements
        for elem in mesh.elements.values():
            # Field descriptions (19 fields):
            # 1: Material reference number
            # 2: Element type number
            # 3: Real constant reference number
            # 4: Section ID
            # 5: Element coordinate system
            # 6: Birth/death flag
            # 7: Solid model reference
            # 8: Element shape flag
            # 9: Number of nodes
            # 10: Not used
            # 11: Element number
            # Then: Node connectivity list

            fields = [
                mat_id,           # Field 1: Material ID
                et_id,            # Field 2: Element type ID
                real_id,          # Field 3: Real constant ID
                secnum,           # Field 4: Section ID
                0,                # Field 5: Coordinate system
                0,                # Field 6: Birth/death flag
                0,                # Field 7: Solid model ref
                0,                # Field 8: Shape flag
                num_nodes_per_elem,  # Field 9: Number of nodes
                0,                # Field 10: Not used
                elem.id           # Field 11: Element number
            ]

            # Fields 12-19: reserved (zeros)
            fields.extend([0] * 8)

            # Write fields (19 integers, 9 chars each)
            line = "".join(f"{f:9d}" for f in fields) + "\n"
            self.file.write(line)

            # Write node connectivity
            # ANSYS format: 8 nodes per line, 9 chars each, right-aligned
            node_ids = elem.nodes
            for i in range(0, len(node_ids), 8):
                chunk = node_ids[i:i+8]
                node_line = "".join(f"{nid:9d}" for nid in chunk) + "\n"
                self.file.write(node_line)

        self.file.write("        -1\n")  # EBLOCK terminator
        self.logger.info(f"Wrote {mesh.num_elements()} elements")

    def _get_nodes_per_element(self, elem_type: ElementType) -> int:
        """Get number of nodes per element"""
        nodes_map = {
            ElementType.HEX8: 8,
            ElementType.HEX20: 20,
            ElementType.HEX27: 27,
            ElementType.TET4: 4,
            ElementType.TET10: 10,
            ElementType.PRISM6: 6,
            ElementType.PYRAMID5: 5,
        }
        return nodes_map.get(elem_type, 8)

    def write_component(self, comp_name: str, comp_type: str, entity_ids: List[int]):
        """
        Write CM (component) command

        Args:
            comp_name: Component name
            comp_type: Component type ('NODE' or 'ELEM')
            entity_ids: List of node or element IDs
        """
        if comp_name in self._written_components:
            self.logger.warning(f"Component '{comp_name}' already written, skipping")
            return

        # CMBLOCK format for efficient large sets
        self.file.write(f"CMBLOCK,{comp_name},{comp_type},{len(entity_ids)}\n")
        self.file.write("(8i10)\n")  # 8 integers per line, 10 chars each

        # Write entity IDs, 8 per line
        for i in range(0, len(entity_ids), 8):
            chunk = entity_ids[i:i+8]
            line = "".join(f"{eid:10d}" for eid in chunk) + "\n"
            self.file.write(line)

        self.logger.debug(f"Wrote component '{comp_name}' with {len(entity_ids)} {comp_type}s")
        self._written_components.add(comp_name)

    def write_material(self, mat_name: str, mat_id: int = 1,
                      youngs: Optional[float] = None,
                      poisson: Optional[float] = None,
                      density: Optional[float] = None,
                      comments: Optional[List[str]] = None):
        """
        Write material properties using MPDATA commands

        Args:
            mat_name: Material name
            mat_id: Material ID
            youngs: Young's modulus (EX)
            poisson: Poisson's ratio (PRXY)
            density: Density (DENS)
            comments: Optional comments
        """
        if comments:
            for comment in comments:
                self.file.write(f"/COM,  {comment}\n")

        self.file.write(f"/COM,  Material {mat_id}: {mat_name}\n")

        if youngs is not None:
            self.file.write(f"MPDATA,EX,{mat_id},1,{youngs:.6e}\n")

        if poisson is not None:
            self.file.write(f"MPDATA,PRXY,{mat_id},1,{poisson:.6e}\n")

        if density is not None:
            self.file.write(f"MPDATA,DENS,{mat_id},1,{density:.6e}\n")

        self.logger.debug(f"Wrote material '{mat_name}' (ID={mat_id})")

    def write_complete_model(self,
                            mesh: MeshData,
                            title: str = "Model",
                            material_name: str = "Material1",
                            et_id: int = 1,
                            mat_id: int = 1,
                            youngs: Optional[float] = None,
                            poisson: Optional[float] = None,
                            density: Optional[float] = None):
        """
        Write a complete ANSYS model with mesh, element type, and material

        Args:
            mesh: Mesh data to export
            title: Model title for header
            material_name: Material name
            et_id: Element type ID (default: 1)
            mat_id: Material ID (default: 1)
            youngs: Young's modulus (optional)
            poisson: Poisson's ratio (optional)
            density: Density (optional)
        """
        self.write_header(title)
        self.write_element_types(mesh, et_id)
        self.write_nodes(mesh)
        self.write_elements(mesh, et_id, mat_id)

        if youngs is not None or poisson is not None or density is not None:
            self.write_material(material_name, mat_id, youngs, poisson, density)

        self.file.write("/COM,\n")
        self.file.write("/COM,  End of input file\n")
        self.file.write("FINISH\n")
        self.logger.info(f"Wrote complete model to {self.output_path}")
