"""
CalculiX INP Format Export
===========================

This module provides functionality to export mesh data to CalculiX INP format.

CalculiX is a free and open-source finite element analysis application that uses
ABAQUS .inp format with some extensions and differences.

Key Features:
- ABAQUS-compatible .inp format
- CalculiX-specific keywords (*BOUNDARY, *CLOAD, *STEP, etc.)
- Node and element definitions
- Material properties (linear and nonlinear)
- Boundary conditions and loads
- Analysis steps

Format Details:
- ASCII text format
- Keyword-based structure (starts with *)
- Case-insensitive keywords
- Line length: typically <256 characters
- Comment lines start with **

Supported Element Types:
- C3D8: 8-node hexahedron
- C3D20: 20-node hexahedron
- C3D27: 27-node hexahedron (via C3D20)
- C3D4: 4-node tetrahedron
- C3D10: 10-node tetrahedron
- C3D6: 6-node prism/wedge
- C3D5: 5-node pyramid (as degenerate C3D8)

Usage:
    >>> from koomesh.export.calculix_writer import CalculixWriter
    >>> from koomesh.meshing.mesh_data import MeshData
    >>>
    >>> # Create and populate mesh
    >>> mesh = MeshData()
    >>> # ... add nodes and elements ...
    >>>
    >>> # Export to CalculiX INP format
    >>> with CalculixWriter("output.inp", title="My Analysis") as writer:
    ...     writer.write_mesh(mesh)
    ...     writer.write_material("Steel", elastic=(210000, 0.3))
    ...     writer.write_boundary_condition("Fixed", [1, 2, 3, 4], dofs=[1, 2, 3])
    ...     writer.write_cload("Load", [100, 101], dof=3, magnitude=1000.0)
    ...     writer.write_step_static()

Author: KooMeshGenerator Team
License: MIT
"""

import logging
from pathlib import Path
from typing import Optional, Dict, List, Tuple

from koomesh.meshing.mesh_data import MeshData, ElementType


class CalculixError(Exception):
    """Exception raised for CalculiX export errors"""
    pass


class CalculixWriter:
    """
    CalculiX INP format writer

    Exports mesh data to CalculiX-compatible ABAQUS .inp format with
    CalculiX-specific features.

    Attributes:
        filepath: Path to output file
        title: Model title/description
        file: File handle

    Example:
        >>> writer = CalculixWriter("model.inp", title="Beam Analysis")
        >>> with writer:
        ...     writer.write_mesh(mesh_data)
        ...     writer.write_material("Steel", elastic=(210000, 0.3))
        ...     writer.write_step_static()
    """

    # CalculiX element type names (ABAQUS-compatible)
    CALCULIX_ELEMENT_TYPES = {
        ElementType.HEX8: "C3D8",
        ElementType.HEX20: "C3D20",
        ElementType.HEX27: "C3D20",  # CalculiX uses C3D20 for 20-node hex
        ElementType.TET4: "C3D4",
        ElementType.TET10: "C3D10",
        ElementType.PRISM6: "C3D6",
        ElementType.PYRAMID5: "C3D8",  # Degenerate hex (node 5=6=7=8)
    }

    def __init__(self, filepath: str, title: str = "CalculiX Model"):
        """
        Initialize CalculiX writer

        Args:
            filepath: Output file path (.inp extension recommended)
            title: Model title/description

        """
        self.filepath = Path(filepath)
        self.title = title
        self.file = None
        self.logger = logging.getLogger(__name__)

        # Ensure proper file extension
        if self.filepath.suffix not in ['.inp', '.INP']:
            self.logger.warning(
                f"File extension {self.filepath.suffix} is non-standard. "
                "Recommended: .inp"
            )

    def __enter__(self):
        """Context manager entry"""
        self.open()
        return self

    def __exit__(self, exc_type, exc_val, exc_tb):
        """Context manager exit"""
        self.close()

    def open(self):
        """Open file for writing"""
        if self.file is not None:
            self.logger.warning("File already open")
            return

        try:
            # Create parent directory if needed
            self.filepath.parent.mkdir(parents=True, exist_ok=True)

            # Open file in text mode
            self.file = open(self.filepath, 'w', encoding='utf-8')

            # Write header
            self.file.write("*HEADING\n")
            self.file.write(f"{self.title}\n")
            self.file.write("** Generated by KooMeshGenerator\n")
            self.file.write("** CalculiX-compatible ABAQUS format\n")

            self.logger.debug(f"Opened CalculiX INP file: {self.filepath}")

        except Exception as e:
            raise CalculixError(f"Failed to open file {self.filepath}: {e}")

    def close(self):
        """Close file"""
        if self.file is not None:
            try:
                self.file.write("*END\n")
                self.file.close()
                self.file = None
                self.logger.debug(f"Closed CalculiX INP file: {self.filepath}")
            except Exception as e:
                self.logger.error(f"Error closing file: {e}")

    def write_mesh(self,
                   mesh: MeshData,
                   elsets: Optional[Dict[str, List[int]]] = None,
                   nsets: Optional[Dict[str, List[int]]] = None):
        """
        Write complete mesh to CalculiX INP file

        Args:
            mesh: MeshData object with nodes and elements
            elsets: Optional dictionary mapping element set names to element IDs
            nsets: Optional dictionary mapping node set names to node IDs

        Raises:
            CalculixError: If file is not open or mesh is invalid

        Example:
            >>> elsets = {"Part1": [1, 2, 3], "Part2": [4, 5, 6]}
            >>> nsets = {"Fixed": [1, 2, 3, 4], "Loaded": [100, 101, 102]}
            >>> writer.write_mesh(mesh, elsets, nsets)
        """
        if self.file is None:
            raise CalculixError("File not open. Use 'with' statement or call open() first.")

        if mesh.num_nodes() == 0:
            raise CalculixError("Mesh has no nodes")

        if mesh.num_elements() == 0:
            raise CalculixError("Mesh has no elements")

        self.logger.info(f"Writing CalculiX mesh: {mesh.num_nodes()} nodes, "
                        f"{mesh.num_elements()} elements")

        # Write nodes
        self._write_nodes(mesh)

        # Write elements (grouped by type)
        self._write_elements(mesh)

        # Write element sets
        if elsets:
            self._write_elsets(elsets)

        # Write node sets
        if nsets:
            self._write_nsets(nsets)

        self.logger.info(f"Successfully wrote mesh to: {self.filepath}")

    def _write_nodes(self, mesh: MeshData):
        """Write nodes section"""
        self.file.write("*NODE\n")

        # Write nodes in sorted order
        for node_id in sorted(mesh.nodes.keys()):
            node = mesh.nodes[node_id]
            self.file.write(f"{node_id}, {node.x:.8e}, {node.y:.8e}, {node.z:.8e}\n")

        self.logger.debug(f"Wrote {mesh.num_nodes()} nodes")

    def _write_elements(self, mesh: MeshData):
        """Write elements section (grouped by type)"""
        # Group elements by type
        elements_by_type = {}
        for elem_id, element in mesh.elements.items():
            elem_type = element.type
            if elem_type not in elements_by_type:
                elements_by_type[elem_type] = []
            elements_by_type[elem_type].append(elem_id)

        # Write each element type group
        for elem_type, elem_ids in elements_by_type.items():
            ccx_type = self.CALCULIX_ELEMENT_TYPES.get(elem_type)
            if ccx_type is None:
                raise CalculixError(f"Unsupported element type: {elem_type}")

            # Write element header
            self.file.write(f"*ELEMENT, TYPE={ccx_type}\n")

            # Write elements
            for elem_id in sorted(elem_ids):
                element = mesh.elements[elem_id]
                nodes = element.nodes

                # Handle PYRAMID5 as degenerate HEX8 (last 4 nodes same)
                if elem_type == ElementType.PYRAMID5:
                    # PYRAMID5: nodes 1-5, make degenerate HEX8: nodes 1-4, 5, 5, 5, 5
                    nodes = nodes[:5] + [nodes[4]] * 3

                # Handle HEX27 as HEX20 (skip center nodes)
                elif elem_type == ElementType.HEX27:
                    # Use first 20 nodes (corner + mid-edge, skip face/center)
                    nodes = nodes[:20]

                # Write element
                self.file.write(f"{elem_id}")
                for node_id in nodes:
                    self.file.write(f", {node_id}")
                self.file.write("\n")

        self.logger.debug(f"Wrote {mesh.num_elements()} elements in {len(elements_by_type)} groups")

    def _write_elsets(self, elsets: Dict[str, List[int]]):
        """Write element sets"""
        for set_name, elem_ids in elsets.items():
            self.file.write(f"*ELSET, ELSET={set_name}\n")

            # Write element IDs (16 per line maximum)
            for i in range(0, len(elem_ids), 16):
                line_ids = elem_ids[i:i+16]
                self.file.write(", ".join(map(str, line_ids)))
                self.file.write("\n")

        self.logger.debug(f"Wrote {len(elsets)} element sets")

    def _write_nsets(self, nsets: Dict[str, List[int]]):
        """Write node sets"""
        for set_name, node_ids in nsets.items():
            self.file.write(f"*NSET, NSET={set_name}\n")

            # Write node IDs (16 per line maximum)
            for i in range(0, len(node_ids), 16):
                line_ids = node_ids[i:i+16]
                self.file.write(", ".join(map(str, line_ids)))
                self.file.write("\n")

        self.logger.debug(f"Wrote {len(nsets)} node sets")

    def write_material(self,
                      name: str,
                      elastic: Optional[Tuple[float, float]] = None,
                      plastic: Optional[List[Tuple[float, float]]] = None,
                      density: Optional[float] = None):
        """
        Write material definition

        Args:
            name: Material name
            elastic: Tuple of (Young's modulus, Poisson's ratio)
            plastic: List of (yield stress, plastic strain) tuples
            density: Material density

        Example:
            >>> writer.write_material("Steel",
            ...                      elastic=(210000, 0.3),
            ...                      plastic=[(250, 0), (400, 0.2)],
            ...                      density=7850)
        """
        if self.file is None:
            raise CalculixError("File not open")

        self.file.write(f"*MATERIAL, NAME={name}\n")

        # Elastic properties
        if elastic:
            E, nu = elastic
            self.file.write("*ELASTIC\n")
            self.file.write(f"{E:.8e}, {nu:.8e}\n")

        # Plastic properties
        if plastic:
            self.file.write("*PLASTIC\n")
            for yield_stress, plastic_strain in plastic:
                self.file.write(f"{yield_stress:.8e}, {plastic_strain:.8e}\n")

        # Density
        if density:
            self.file.write("*DENSITY\n")
            self.file.write(f"{density:.8e}\n")

        self.logger.debug(f"Wrote material: {name}")

    def write_solid_section(self, elset: str, material: str):
        """
        Write solid section definition

        Args:
            elset: Element set name
            material: Material name

        Example:
            >>> writer.write_solid_section("Part1", "Steel")
        """
        if self.file is None:
            raise CalculixError("File not open")

        self.file.write(f"*SOLID SECTION, ELSET={elset}, MATERIAL={material}\n")
        self.logger.debug(f"Wrote solid section: {elset} -> {material}")

    def write_boundary_condition(self,
                                 nset: str,
                                 dofs: List[int],
                                 values: Optional[List[float]] = None):
        """
        Write boundary condition

        Args:
            nset: Node set name
            dofs: List of DOFs to constrain (1=X, 2=Y, 3=Z, etc.)
            values: Optional prescribed values (None = fixed)

        Example:
            >>> # Fix all DOFs
            >>> writer.write_boundary_condition("Fixed", [1, 2, 3])
            >>>
            >>> # Prescribe displacement
            >>> writer.write_boundary_condition("Moved", [1], [0.01])
        """
        if self.file is None:
            raise CalculixError("File not open")

        self.file.write(f"*BOUNDARY\n")

        # If no values provided, fix all DOFs
        if values is None:
            values = [0.0] * len(dofs)

        # Write boundary conditions
        for dof, value in zip(dofs, values):
            self.file.write(f"{nset}, {dof}, {dof}, {value:.8e}\n")

        self.logger.debug(f"Wrote boundary condition for {nset}")

    def write_cload(self,
                   nset: str,
                   dof: int,
                   magnitude: float):
        """
        Write concentrated load

        Args:
            nset: Node set name
            dof: DOF to apply load (1=X, 2=Y, 3=Z, etc.)
            magnitude: Load magnitude

        Example:
            >>> writer.write_cload("TopNodes", 3, -1000.0)  # -1000 in Z direction
        """
        if self.file is None:
            raise CalculixError("File not open")

        self.file.write(f"*CLOAD\n")
        self.file.write(f"{nset}, {dof}, {magnitude:.8e}\n")

        self.logger.debug(f"Wrote concentrated load on {nset}")

    def write_dload(self,
                   elset: str,
                   load_type: str,
                   magnitude: float):
        """
        Write distributed load

        Args:
            elset: Element set name
            load_type: Load type (e.g., "P" for pressure, "GRAV" for gravity)
            magnitude: Load magnitude

        Example:
            >>> writer.write_dload("Surface", "P", 100.0)  # 100 Pa pressure
        """
        if self.file is None:
            raise CalculixError("File not open")

        self.file.write(f"*DLOAD\n")
        self.file.write(f"{elset}, {load_type}, {magnitude:.8e}\n")

        self.logger.debug(f"Wrote distributed load on {elset}")

    def write_step_static(self,
                         initial_inc: float = 0.1,
                         total_time: float = 1.0,
                         min_inc: float = 1e-5,
                         max_inc: float = 1.0):
        """
        Write static analysis step

        Args:
            initial_inc: Initial increment size
            total_time: Total step time
            min_inc: Minimum increment size
            max_inc: Maximum increment size

        Example:
            >>> writer.write_step_static(initial_inc=0.1, total_time=1.0)
        """
        if self.file is None:
            raise CalculixError("File not open")

        self.file.write("*STEP\n")
        self.file.write("*STATIC\n")
        self.file.write(f"{initial_inc:.8e}, {total_time:.8e}, {min_inc:.8e}, {max_inc:.8e}\n")
        self.file.write("*END STEP\n")

        self.logger.debug("Wrote static analysis step")

    def write_output_requests(self,
                             node_output: Optional[List[str]] = None,
                             element_output: Optional[List[str]] = None):
        """
        Write output requests

        Args:
            node_output: List of node output variables (e.g., ["U", "RF"])
            element_output: List of element output variables (e.g., ["S", "E"])

        Example:
            >>> writer.write_output_requests(
            ...     node_output=["U", "RF"],      # Displacement, Reaction force
            ...     element_output=["S", "E"]      # Stress, Strain
            ... )
        """
        if self.file is None:
            raise CalculixError("File not open")

        # Node output
        if node_output:
            self.file.write("*NODE FILE\n")
            self.file.write(", ".join(node_output))
            self.file.write("\n")

        # Element output
        if element_output:
            self.file.write("*EL FILE\n")
            self.file.write(", ".join(element_output))
            self.file.write("\n")

        self.logger.debug("Wrote output requests")


def export_to_calculix(mesh: MeshData,
                       filepath: str,
                       title: str = "CalculiX Model",
                       elsets: Optional[Dict[str, List[int]]] = None,
                       nsets: Optional[Dict[str, List[int]]] = None) -> bool:
    """
    Convenience function to export mesh to CalculiX format

    Args:
        mesh: MeshData object
        filepath: Output file path
        title: Model title
        elsets: Optional element sets
        nsets: Optional node sets

    Returns:
        True if export succeeded, False otherwise

    Example:
        >>> from koomesh.meshing.mesh_data import MeshData
        >>> mesh = MeshData()
        >>> # ... populate mesh ...
        >>> success = export_to_calculix(mesh, "model.inp", title="Beam")
    """
    try:
        with CalculixWriter(filepath, title=title) as writer:
            writer.write_mesh(mesh, elsets, nsets)
        return True
    except Exception as e:
        logging.getLogger(__name__).error(f"CalculiX export failed: {e}")
        return False
