"""
Nastran Bulk Data File Writer
==============================

This module exports meshes to Nastran .bdf (Bulk Data File) format.

Features:
- GRID (node definition)
- CHEXA, CTETRA, CPENTA, CPYRAM (element definitions)
- MAT1 (isotropic material properties)
- PSOLID (solid element properties)
- SET1 (node/element sets)
- Fixed and free format support

Nastran Element Type Mapping:
- HEX8 -> CHEXA (8-node hexahedron)
- HEX20 -> CHEXA (20-node hexahedron)
- HEX27 -> CHEXA (27-node not standard, uses 20)
- TET4 -> CTETRA (4-node tetrahedron)
- TET10 -> CTETRA (10-node tetrahedron)
- PRISM6 -> CPENTA (6-node pentahedron/wedge)
- PYRAMID5 -> CPYRAM (5-node pyramid)

Usage:
    >>> from koomesh.export.nastran_writer import NastranWriter
    >>> writer = NastranWriter('output.bdf')
    >>> writer.write_mesh(mesh)

    Or using context manager:
    >>> with NastranWriter('output.bdf', format='large') as writer:
    ...     writer.write_header("My Model")
    ...     writer.write_nodes(mesh)
    ...     writer.write_elements(mesh, pid=1)
    ...     writer.write_material(1, youngs=210000, poisson=0.3)
    ...     writer.write_property(1, mat_id=1)
"""

import logging
from pathlib import Path
from typing import List, Optional, Dict, Set
from datetime import datetime

from koomesh.meshing.mesh_data import MeshData, ElementType


class NastranWriter:
    """
    Nastran bulk data file (.bdf) writer

    This class writes mesh data to Nastran format with support for:
    - Node definitions (GRID)
    - Element definitions (CHEXA, CTETRA, CPENTA, CPYRAM)
    - Material properties (MAT1)
    - Property definitions (PSOLID)
    - Sets (SET1)
    - Fixed and large field formats

    Attributes:
        output_path: Output file path
        format: Field format ('small' or 'large')
        precision: Number of decimal places for coordinates
        logger: Logger instance

    Example:
        >>> writer = NastranWriter('model.bdf', format='large')
        >>> with writer:
        ...     writer.write_header("Analysis Model")
        ...     writer.write_nodes(mesh)
        ...     writer.write_elements(mesh, pid=1)
        ...     writer.write_property(1, mat_id=1)
        ...     writer.write_material(1, youngs=210000, poisson=0.3)
    """

    # Element type mapping: KooMesh -> Nastran
    ELEMENT_TYPE_MAP = {
        ElementType.HEX8: "CHEXA",
        ElementType.HEX20: "CHEXA",
        ElementType.HEX27: "CHEXA",  # Will use 20-node
        ElementType.TET4: "CTETRA",
        ElementType.TET10: "CTETRA",
        ElementType.PRISM6: "CPENTA",
        ElementType.PYRAMID5: "CPYRAM",
    }

    def __init__(self,
                 output_path: str,
                 format: str = 'large',
                 precision: int = 8):
        """
        Initialize Nastran writer

        Args:
            output_path: Output .bdf file path
            format: Field format - 'small' (8 char) or 'large' (16 char) (default: 'large')
            precision: Decimal places for floating point numbers (default: 8)
        """
        self.output_path = Path(output_path)
        self.format = format
        self.precision = precision
        self.logger = logging.getLogger(__name__)

        self.file = None
        self._written_sets = set()  # Track written sets

    def __enter__(self):
        """Context manager entry"""
        self.file = open(self.output_path, 'w')
        return self

    def __exit__(self, exc_type, exc_val, exc_tb):
        """Context manager exit"""
        if self.file:
            self.file.close()

    def write_header(self, title: str = "KooMesh Model", comments: Optional[List[str]] = None):
        """
        Write Nastran file header

        Args:
            title: Model title
            comments: Optional list of comment lines
        """
        self.file.write("$*******************************************************************************\n")
        self.file.write(f"$ {title}\n")
        self.file.write("$ Generated by KooMeshGenerator\n")
        self.file.write(f"$ Date: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}\n")
        self.file.write("$*******************************************************************************\n")

        if comments:
            for comment in comments:
                self.file.write(f"$ {comment}\n")

        self.file.write("$\n")
        self.file.write("BEGIN BULK\n")
        self.logger.debug("Wrote header")

    def write_nodes(self, mesh: MeshData, cp: int = 0, cd: int = 0, ps: int = 0):
        """
        Write GRID (node) entries

        Nastran GRID format:
        Small field (8 char):  GRID,ID,CP,X,Y,Z,CD,PS,SEID
        Large field (16 char): GRID*,ID,CP,X,Y,
                               *,Z,CD,PS,SEID

        Args:
            mesh: Mesh containing nodes
            cp: Coordinate system for position (default: 0)
            cd: Coordinate system for displacement (default: 0)
            ps: Permanent single-point constraints (default: 0)
        """
        self.file.write("$\n")
        self.file.write("$ Nodes\n")
        self.file.write("$\n")

        if self.format == 'large':
            # Large field format (16 characters per field)
            for node in mesh.nodes.values():
                # Line 1: GRID*, ID, CP, X, Y
                line1 = f"GRID*   {node.id:16d}{cp:16d}{node.x:16.{self.precision}E}{node.y:16.{self.precision}E}\n"
                # Line 2: *,      Z, CD, PS, SEID
                line2 = f"*       {node.z:16.{self.precision}E}{cd:16d}{ps:16d}\n"
                self.file.write(line1)
                self.file.write(line2)
        else:
            # Small field format (8 characters per field)
            for node in mesh.nodes.values():
                # GRID, ID, CP, X, Y, Z, CD, PS, SEID
                line = f"GRID    {node.id:8d}{cp:8d}{node.x:8.{self.precision}E}{node.y:8.{self.precision}E}\n"
                line += f"        {node.z:8.{self.precision}E}{cd:8d}{ps:8d}\n"
                self.file.write(line)

        self.logger.info(f"Wrote {mesh.num_nodes()} nodes")

    def write_elements(self, mesh: MeshData, pid: int = 1):
        """
        Write element entries (CHEXA, CTETRA, CPENTA, CPYRAM)

        Args:
            mesh: Mesh containing elements
            pid: Property ID (default: 1)
        """
        self.file.write("$\n")
        self.file.write("$ Elements\n")
        self.file.write("$\n")

        nastran_type = self._get_nastran_element_type(mesh.element_type)

        if mesh.element_type.is_hex():
            self._write_hex_elements(mesh, pid, nastran_type)
        elif mesh.element_type.is_tet():
            self._write_tet_elements(mesh, pid, nastran_type)
        elif mesh.element_type == ElementType.PRISM6:
            self._write_prism_elements(mesh, pid, nastran_type)
        elif mesh.element_type == ElementType.PYRAMID5:
            self._write_pyramid_elements(mesh, pid, nastran_type)
        else:
            raise ValueError(f"Element type {mesh.element_type.code} not supported")

        self.logger.info(f"Wrote {mesh.num_elements()} {nastran_type} elements")

    def _get_nastran_element_type(self, elem_type: ElementType) -> str:
        """Get Nastran element type name"""
        if elem_type not in self.ELEMENT_TYPE_MAP:
            raise ValueError(f"Element type {elem_type.code} not supported in Nastran export")
        return self.ELEMENT_TYPE_MAP[elem_type]

    def _write_hex_elements(self, mesh: MeshData, pid: int, elem_type: str):
        """Write CHEXA elements"""
        for elem in mesh.elements.values():
            node_ids = elem.nodes

            if self.format == 'large':
                # Large field format
                # Line 1: CHEXA*, EID, PID, G1, G2
                line1 = f"{elem_type}*  {elem.id:16d}{pid:16d}{node_ids[0]:16d}{node_ids[1]:16d}\n"
                # Line 2: *, G3, G4, G5, G6
                line2 = f"*       {node_ids[2]:16d}{node_ids[3]:16d}{node_ids[4]:16d}{node_ids[5]:16d}\n"
                # Line 3: *, G7, G8
                line3 = f"*       {node_ids[6]:16d}{node_ids[7]:16d}\n"

                self.file.write(line1)
                self.file.write(line2)
                self.file.write(line3)

                # If HEX20, write additional nodes
                if mesh.element_type == ElementType.HEX20:
                    # Line 4: *, G9, G10, G11, G12
                    line4 = f"*       {node_ids[8]:16d}{node_ids[9]:16d}{node_ids[10]:16d}{node_ids[11]:16d}\n"
                    # Line 5: *, G13, G14, G15, G16
                    line5 = f"*       {node_ids[12]:16d}{node_ids[13]:16d}{node_ids[14]:16d}{node_ids[15]:16d}\n"
                    # Line 6: *, G17, G18, G19, G20
                    line6 = f"*       {node_ids[16]:16d}{node_ids[17]:16d}{node_ids[18]:16d}{node_ids[19]:16d}\n"
                    self.file.write(line4)
                    self.file.write(line5)
                    self.file.write(line6)
            else:
                # Small field format
                # CHEXA, EID, PID, G1, G2, G3, G4, G5, G6
                line1 = f"{elem_type:8s}{elem.id:8d}{pid:8d}{node_ids[0]:8d}{node_ids[1]:8d}{node_ids[2]:8d}{node_ids[3]:8d}{node_ids[4]:8d}\n"
                line2 = f"        {node_ids[5]:8d}{node_ids[6]:8d}{node_ids[7]:8d}\n"
                self.file.write(line1)
                self.file.write(line2)

                if mesh.element_type == ElementType.HEX20:
                    line3 = f"        {node_ids[8]:8d}{node_ids[9]:8d}{node_ids[10]:8d}{node_ids[11]:8d}{node_ids[12]:8d}{node_ids[13]:8d}{node_ids[14]:8d}\n"
                    line4 = f"        {node_ids[15]:8d}{node_ids[16]:8d}{node_ids[17]:8d}{node_ids[18]:8d}{node_ids[19]:8d}\n"
                    self.file.write(line3)
                    self.file.write(line4)

    def _write_tet_elements(self, mesh: MeshData, pid: int, elem_type: str):
        """Write CTETRA elements"""
        for elem in mesh.elements.values():
            node_ids = elem.nodes

            if self.format == 'large':
                # CTETRA*, EID, PID, G1, G2
                line1 = f"{elem_type}* {elem.id:16d}{pid:16d}{node_ids[0]:16d}{node_ids[1]:16d}\n"
                # *, G3, G4
                line2 = f"*       {node_ids[2]:16d}{node_ids[3]:16d}\n"
                self.file.write(line1)
                self.file.write(line2)

                if mesh.element_type == ElementType.TET10:
                    # *, G5, G6, G7, G8
                    line3 = f"*       {node_ids[4]:16d}{node_ids[5]:16d}{node_ids[6]:16d}{node_ids[7]:16d}\n"
                    # *, G9, G10
                    line4 = f"*       {node_ids[8]:16d}{node_ids[9]:16d}\n"
                    self.file.write(line3)
                    self.file.write(line4)
            else:
                # Small format
                line = f"{elem_type:8s}{elem.id:8d}{pid:8d}{node_ids[0]:8d}{node_ids[1]:8d}{node_ids[2]:8d}{node_ids[3]:8d}\n"
                self.file.write(line)

                if mesh.element_type == ElementType.TET10:
                    line2 = f"        {node_ids[4]:8d}{node_ids[5]:8d}{node_ids[6]:8d}{node_ids[7]:8d}{node_ids[8]:8d}{node_ids[9]:8d}\n"
                    self.file.write(line2)

    def _write_prism_elements(self, mesh: MeshData, pid: int, elem_type: str):
        """Write CPENTA elements"""
        for elem in mesh.elements.values():
            node_ids = elem.nodes

            if self.format == 'large':
                # CPENTA*, EID, PID, G1, G2
                line1 = f"{elem_type}* {elem.id:16d}{pid:16d}{node_ids[0]:16d}{node_ids[1]:16d}\n"
                # *, G3, G4, G5, G6
                line2 = f"*       {node_ids[2]:16d}{node_ids[3]:16d}{node_ids[4]:16d}{node_ids[5]:16d}\n"
                self.file.write(line1)
                self.file.write(line2)
            else:
                line = f"{elem_type:8s}{elem.id:8d}{pid:8d}{node_ids[0]:8d}{node_ids[1]:8d}{node_ids[2]:8d}{node_ids[3]:8d}{node_ids[4]:8d}\n"
                line2 = f"        {node_ids[5]:8d}\n"
                self.file.write(line)
                self.file.write(line2)

    def _write_pyramid_elements(self, mesh: MeshData, pid: int, elem_type: str):
        """Write CPYRAM elements"""
        for elem in mesh.elements.values():
            node_ids = elem.nodes

            if self.format == 'large':
                # CPYRAM*, EID, PID, G1, G2
                line1 = f"{elem_type}* {elem.id:16d}{pid:16d}{node_ids[0]:16d}{node_ids[1]:16d}\n"
                # *, G3, G4, G5
                line2 = f"*       {node_ids[2]:16d}{node_ids[3]:16d}{node_ids[4]:16d}\n"
                self.file.write(line1)
                self.file.write(line2)
            else:
                line = f"{elem_type:8s}{elem.id:8d}{pid:8d}{node_ids[0]:8d}{node_ids[1]:8d}{node_ids[2]:8d}{node_ids[3]:8d}{node_ids[4]:8d}\n"
                self.file.write(line)

    def write_property(self, pid: int, mat_id: int, cordm: int = 0, stress_input: str = "GRID"):
        """
        Write PSOLID (solid property) entry

        Args:
            pid: Property ID
            mat_id: Material ID
            cordm: Material coordinate system (default: 0)
            stress_input: Stress output location (default: "GRID")
        """
        self.file.write("$\n")
        self.file.write("$ Property\n")
        self.file.write("$\n")

        if self.format == 'large':
            line = f"PSOLID* {pid:16d}{mat_id:16d}{cordm:16d}{stress_input:>16s}\n"
        else:
            line = f"PSOLID  {pid:8d}{mat_id:8d}{cordm:8d}{stress_input:>8s}\n"

        self.file.write(line)
        self.logger.debug(f"Wrote property PID={pid}, MID={mat_id}")

    def write_material(self, mat_id: int,
                      youngs: Optional[float] = None,
                      shear: Optional[float] = None,
                      poisson: Optional[float] = None,
                      density: Optional[float] = None,
                      thermal_exp: Optional[float] = None,
                      comments: Optional[List[str]] = None):
        """
        Write MAT1 (isotropic material) entry

        Args:
            mat_id: Material ID
            youngs: Young's modulus (E)
            shear: Shear modulus (G)
            poisson: Poisson's ratio (NU)
            density: Density (RHO)
            thermal_exp: Thermal expansion coefficient (A)
            comments: Optional comments
        """
        self.file.write("$\n")
        if comments:
            for comment in comments:
                self.file.write(f"$ {comment}\n")
        self.file.write(f"$ Material {mat_id}\n")
        self.file.write("$\n")

        # Calculate shear modulus if not provided
        if shear is None and youngs is not None and poisson is not None:
            shear = youngs / (2.0 * (1.0 + poisson))

        if self.format == 'large':
            # MAT1*, MID, E, G, NU
            line1 = f"MAT1*   {mat_id:16d}"
            line1 += f"{youngs:16.{self.precision}E}" if youngs else f"{'':16s}"
            line1 += f"{shear:16.{self.precision}E}" if shear else f"{'':16s}"
            line1 += f"{poisson:16.{self.precision}E}" if poisson else f"{'':16s}"
            line1 += "\n"

            # *, RHO, A
            line2 = "*       "
            line2 += f"{density:16.{self.precision}E}" if density else f"{'':16s}"
            line2 += f"{thermal_exp:16.{self.precision}E}" if thermal_exp else f"{'':16s}"
            line2 += "\n"

            self.file.write(line1)
            self.file.write(line2)
        else:
            # MAT1, MID, E, G, NU, RHO, A
            line = f"MAT1    {mat_id:8d}"
            line += f"{youngs:8.2E}" if youngs else f"{'':8s}"
            line += f"{shear:8.2E}" if shear else f"{'':8s}"
            line += f"{poisson:8.{self.precision}f}" if poisson else f"{'':8s}"
            line += f"{density:8.2E}" if density else f"{'':8s}"
            line += "\n"
            # Continuation for thermal expansion if needed
            if thermal_exp:
                line += f"        {thermal_exp:8.2E}\n"

            self.file.write(line)

        self.logger.debug(f"Wrote material MID={mat_id}")

    def write_set(self, set_id: int, set_type: str, entity_ids: List[int]):
        """
        Write SET1 entry

        Args:
            set_id: Set ID
            set_type: Set type (not used in SET1, kept for API consistency)
            entity_ids: List of node or element IDs
        """
        if set_id in self._written_sets:
            self.logger.warning(f"Set {set_id} already written, skipping")
            return

        self.file.write("$\n")
        self.file.write(f"$ Set {set_id}\n")
        self.file.write("$\n")

        if self.format == 'large':
            # SET1*, SID, ID1, ID2, ID3
            # Write in chunks of 3 IDs per continuation line
            line = f"SET1*   {set_id:16d}"
            for i, eid in enumerate(entity_ids):
                if i > 0 and i % 3 == 0:
                    line += "\n*       "
                line += f"{eid:16d}"
            line += "\n"
            self.file.write(line)
        else:
            # SET1, SID, ID1, ID2, ..., ID7
            # Write in chunks of 7 IDs per continuation line
            line = f"SET1    {set_id:8d}"
            for i, eid in enumerate(entity_ids):
                if i > 0 and i % 7 == 0:
                    line += "\n        "
                line += f"{eid:8d}"
            line += "\n"
            self.file.write(line)

        self._written_sets.add(set_id)
        self.logger.debug(f"Wrote set SID={set_id} with {len(entity_ids)} entities")

    def write_complete_model(self,
                            mesh: MeshData,
                            title: str = "Model",
                            pid: int = 1,
                            mat_id: int = 1,
                            youngs: Optional[float] = None,
                            poisson: Optional[float] = None,
                            density: Optional[float] = None):
        """
        Write a complete Nastran model with mesh, property, and material

        Args:
            mesh: Mesh data to export
            title: Model title for header
            pid: Property ID (default: 1)
            mat_id: Material ID (default: 1)
            youngs: Young's modulus (optional)
            poisson: Poisson's ratio (optional)
            density: Density (optional)
        """
        self.write_header(title)
        self.write_nodes(mesh)
        self.write_elements(mesh, pid)
        self.write_property(pid, mat_id)

        if youngs is not None or poisson is not None or density is not None:
            self.write_material(mat_id, youngs=youngs, poisson=poisson, density=density)

        self.file.write("$\n")
        self.file.write("ENDDATA\n")
        self.logger.info(f"Wrote complete model to {self.output_path}")
